---
title: "BMDCs internalization"
author: "Lakshmi Batachari"
date: "2/4/2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(shiny)
library(dbplyr)
library(openxlsx)
library(tidyverse)
theme_set(theme_classic())
```

```{r}
#read the file
BMDCs <- read.xlsx("internalization.xlsx")
```

```{r}
meanRatio <- BMDCs %>%
  group_by(name, mouse, strain) %>%
  summarize(averageIntact = mean(intactRatio), sdIntact = sd(intactRatio)) %>%
  mutate(upperError = averageIntact + sdIntact, lowerError = averageIntact - sdIntact)

w <- 0.6
pos <-  position_dodge(width = w)

ggplot(meanRatio, aes(x = mouse, y = averageIntact, fill = strain)) +
  geom_bar(stat = "identity", color = "black", width = w, position = position_dodge()) +
  geom_errorbar(aes(ymax = upperError, ymin= averageIntact),  width = .2, position = pos) +
  #geom_point(aes(x= mouse, y = averageIntact), position = pos) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Mouse", y = "Ratio of B.fragilis Intact" ) +
  coord_cartesian(ylim = c(0,1.2)) +
  scale_fill_discrete(name = "B.fragilis") +
  scale_x_discrete(limits = c("ATG16L1 KO", "NOD2 KO", "Rubicon KO", "TLR2 KO", "C57BL/6"))
  
```


